config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/' => "users#root"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  resources :users do
    resources :ideas
  end

  namespace :admin do
    resources :categories
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true

  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, presence: true

  belongs_to :category
  belongs_to :user

  has_many :ideas_images
  has_many :images, through: :ideas_images

  def self.sort_by_category
    order(:category_id)
  end

end

app/models/ideaimage.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

app/models/ideas_image.rb
class IdeasImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, presence: true

  has_many :ideas_images
  has_many :ideas, through: :ideas_images
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_confirmation_of :password

  validates :name, presence: true
  has_many :ideas

  enum role: [:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @admin = User.find(session[:user_id])
  end

  def create
    category = Category.new(category_params)
    category.save
    redirect_to admin_categories_path
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @idea = Idea.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @user = User.find(params[:user_id])
    @idea = @user.ideas.new(idea_params)
    @idea.category_id = params[:idea][:category_id].to_i
    if @idea.save
      flash[:success] = "Wow what a great idea!"
      redirect_to user_path(@user)
    else
      flash[:error] = "Hmmm that didn't save for some reason, please try again"
      redirect_to new_user_idea_path(@user)
    end
  end

  def show
    @idea = Idea.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def index
    @user = User.find(params[:user_id])
    @ideas = @user.ideas
  end

  def destroy
    @user = User.find(params[:user_id])
    idea = Idea.find(params[:id])
    idea.delete
    redirect_to user_path(@user)
  end

  def edit
    @idea = Idea.find(params[:id])
    @user = User.find(params[:user_id])
    @categories = Category.all
  end

  def update
    @idea = Idea.find(params[:id])
    @user = User.find(params[:user_id])
    @idea.update(idea_params)

    if @idea.save
      redirect_to user_idea_path(@user, @idea)
    else
      render :edit
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :notes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:email])

    if @user == nil
      render :new
    else
      @user.authenticate(params[:password])
      flash[:success] = "Succesfull logged in!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:success] = "Successfully logged out!"
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def root
    render :root
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully created new user!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1> Current Categories </h1>

  <% @categories.each do |category| %>
    <p><%= category.name %></p> <br>
<% end %>

<%= link_to "Add Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>Add A New Category</h1>


<%= form_for [@admin, @category], :url => admin_categories_path do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1> Edit Your Idea: <%= @idea.title %> </h1>

<%= form_for [@user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :notes %>
  <%= f.text_field :notes %>

  <%= f.collection_select(:category_id, @categories, :id, :name) %>

  <%= f.submit "Create" %>
<% end %>

app/views/ideas/index.html.erb
<h1>Here are all your ideas</h1>

<% @ideas.each do |idea| %>
  <%= link_to idea.title, user_idea_path(@user, idea)  %> <br>
  <%= idea.description %> <br>
  <%= idea.notes %> <br>
  <%= idea.category.name %> <br> <br>

<% end %>

app/views/ideas/new.html.erb
<h1>Enter Your Fabulous Idea! :)</h1>

<%= form_for [@user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :notes %>
  <%= f.text_field :notes %>

  <%= f.collection_select(:category_id, @categories, :id, :name) %>

  <%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<h1> Your Idea: </h1>

<p>Idea: <%= @idea.title %> </p>
<p>Description: <%= @idea.description %> </p>
<p>Notes: <%= @idea.notes %> </p>

<%= link_to "Edit Idea", edit_user_idea_path(@user, @idea) %>
<%= link_to "Delete Idea", user_idea_path, method: "delete" %>
<%= link_to "Ideas Index", user_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/application.css">
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">IdeaBox</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <div class="navbar-right">
          <div class="nav navbar-nav">
            <% if logged_in?  %>
              <div type="button" class="btn btn-default navbar-btn navbar-right">   <%= link_to "Logout", logout_path, method: 'delete' %> </div>
              <div type="button" class="btn btn-default navbar-btn navbar-right"><%= link_to "Add New Idea", new_user_idea_path(@user) %> </div>
        <% else %>
          <div type="button" class="btn btn-default navbar-btn navbar-right">   <%= link_to "Login", login_path %> </div>
          <div type="button" class="btn btn-default navbar-btn navbar-right"><%= link_to "Sign Up", new_user_path %> </div>
          </div>
        </div>
        <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% flash.each do |key, value| %>
    <div class="alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>

    <%= yield %>
    <!-- <% if logged_in? %>
      <%= link_to "Logout", logout_path, method: 'delete' %>
    <% end  %> -->



    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='/js/bootstrap.js'></script>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign Yourself Up! </h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%=  f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/root.html.erb
<h1> Welcome to Idea Box</h1>

app/views/users/show.html.erb
<h1> Welcome <%= @user.name %> </h1>
  <h3>Here are your wonderful ideas:</h3>


<% @user.ideas.sort_by_category.each do |idea| %>
<!-- add photo to idea -->

  <strong> <%= idea.category.name.upcase %> IDEA: </strong>
  <%= link_to idea.title, user_idea_path(@user, idea)  %> <br>
    DESCRIPTION:  <%= idea.description %> <br>
    NOTES:  <%= idea.notes %> <br>

<%= link_to "Edit", edit_user_idea_path(@user, idea)%>
<%= link_to "Delete Idea", user_idea_path(@user, idea), method: "delete" %> <br> <br>
<% end %>

<%= link_to "Add New Idea", new_user_idea_path(@user) %>

<% if @user.role == "admin" %>
<h3> Hello Admin click below to view and add a categories </h3>
<%= link_to "Add Category", admin_categories_path %>
<% end %>